#ifndef JASS_MOUSEBUTTONCODES
#define JASS_MOUSEBUTTONCODES

#ifdef JASS_PLATFORM_WINDOWS

	//from glfw3
	#define JASS_MOUSE_BUTTON_1         0
	#define JASS_MOUSE_BUTTON_2         1
	#define JASS_MOUSE_BUTTON_3         2
	#define JASS_MOUSE_BUTTON_4         3
	#define JASS_MOUSE_BUTTON_5         4
	#define JASS_MOUSE_BUTTON_6         5
	#define JASS_MOUSE_BUTTON_7         6
	#define JASS_MOUSE_BUTTON_8         7
	#define JASS_MOUSE_BUTTON_LAST      JASS_MOUSE_BUTTON_8
	#define JASS_MOUSE_BUTTON_LEFT      JASS_MOUSE_BUTTON_1
	#define JASS_MOUSE_BUTTON_RIGHT     JASS_MOUSE_BUTTON_2
	#define JASS_MOUSE_BUTTON_MIDDLE    JASS_MOUSE_BUTTON_3

#endif // JASS_PLATFORM_WINDOWS

#endif // !JASS_MOUSEBUTTONCODES
